import type { Metadata } from "next";
import { Poppins } from "next/font/google"; // Import Poppins from next/font/google
import "./globals.css";
import Header from "@/components/header";
import { Toaster } from "@/components/ui/toaster";
import { SessionProvider } from "next-auth/react";
import { auth } from "@/auth";
import { ModalProvider } from "@/components/providers/modals-provider";

// Use Poppins font from Google Fonts
const poppins = Poppins({
  subsets: ["latin"], // Add more subsets if needed (e.g., "latin-ext" for extended characters)
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // You can specify multiple weights here
  variable: "--font-poppins", // Set the CSS variable for customization
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body
        className={`${poppins.variable} antialiased marker:bg-slate-600`} // Apply the Poppins font globally
      >
        <SessionProvider session={session}>
          <ModalProvider />
          {session?.user ? <h1></h1> : <Header />}
          {children}
          <Toaster />
        </SessionProvider>
      </body>
    </html>
  );
}
